sudo: required
branches:
  - master
  - prod

services:
  - docker

before_install:
  - docker build -t hungpmpercy/wedvn ./server

script:
  - docker run -e CI=true hungpmpercy/wedvn npm run test:coverage
