version: '3'

services:
  wedvn-server:
    build:
      context: ./server
    ports:
      - '5000:5000'
  nginx:
    depends_on:
      - wedvn-server
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./deploy/data/nginx:/etc/nginx/conf.d
      - ./deploy/data/certbot/conf:/etc/letsencrypt
      - ./deploy/data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    # reload nginx configuration every 6 hours
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    depends_on:
      - wedvn-server
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./deploy/data/certbot/conf:/etc/letsencrypt
      - ./deploy/data/certbot/www:/var/www/certbot
    # check and renew ssl certificate every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
